group1:
  - '#cluster-wide' # this grants the group to skip enforcement
user1:
  - hogarama # single namespace
user3:
  - grafana # multi namespace
  - opernshift-logging
  - opernshift-monitoring
