group1:
  namespace:
    - '#cluster-wide' # this grants the group to skip enforcement
user1:
  namespace:
    - hogarama # single namespace
user3:
  namespace:
    - grafana # multi namespace
    - opernshift-logging
    - opernshift-monitoring
